name: 'Vitalik Action'
description: 'The updater'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Update lock
      shell: bash
      run: |
        rm package-lock.json
        ./gradlew :kotlinStorePackageLock

    - id: modified-files
      name: Check modified files
      shell: bash
      run: |
        echo "list=$( git ls-files --modified )" >> "$GITHUB_OUTPUT"

    - name: Commit changes
      if: steps.modified-files.outputs.list == 'package-lock.json'
      shell: bash
      run: |
        git add package-lock.json
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        git commit -m "Update \`package-lock.json\`"

    - name: Push changes
      if: steps.modified-files.outputs.list == 'package-lock.json'
      shell: bash
      run: |
        git push https://${{ github.token }}@github.com/${{ github.repository }}.git

branding:
  icon: 'lock'
  color: 'orange'
